name: Deploy Default ACA Demo

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Location'
        required: true
        default: 'northeurope'
      base-name:
        description: 'Base name'
        required: true
  
permissions:
  id-token: write
  contents: read
  
jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script file
        uses: azure/cli@v2
        with:
            inlineScript: |
              LOCATION=${{ inputs.location }} 
              BASE_NAME=${{ inputs.base-name }}
              RESOURCE_GROUP_NAME=$BASE_NAME-rg
              DEPLOYMENT_NAME=$BASE_NAME-deployment-$(date +%s)
              if [ $(az group exists --name $RESOURCE_GROUP_NAME) = false ]; then
                az group create --name $RESOURCE_GROUP_NAME --location $LOCATION
              fi
              az deployment group create --name $DEPLOYMENT_NAME --resource-group $RESOURCE_GROUP_NAME --template-file infra/main.bicep --parameters parameters.default.json
        env:
          LOCATION: ${{ inputs.location }}
          BASE_NAME: ${{ inputs.base-name }}